language: node_js
# TODO: break out browsers into matrix

node_js:
  - 10
stages:
  - test
  - deploy
before_script:
  - "npm run build"
jobs:
  include:
    - stage: test
      addons:
        chrome: stable
        firefox: latest
        code_climate:
          repo_token: $CC_TEST_REPORTER_ID
      before_script:
        - npm install --global codeclimate-test-reporter
        - npm run build
      script: npm test
      after_script:
        - codeclimate-test-reporter < ./coverage/lcov.info
    - stage: npm release
      script: "echo releasing npm package..."
      deploy:
        provider: npm
        email: jeremy@burnbright.net
        access: public
        api_key:
          secure: f4BF1MIiOOTPOkS9XyB/HmeWv6OKcR/xx8+Ij4g3M5HSTnzjVMoPZl0XJc9f8Ltfz63hHWe0gcjbhgmApA7hj4nhPX/w+bROw3hAnspwM/m6ABjejEn9+6b2cgHDQ7fdX7gWPitMmgv+Kbq8c2sP+kg8sG1UawWLpxoyGHjIqApiweXU/AqP5aLXsegVGXjHrRnmvafV2QJ3O+2viU0chf7Lg2XAZihODw4kWVZZxN/ZQaPDYS96FrGP4wNPySrWwxs7z1W4zqFAOkkgP5W5ha9F1YVkCPYIqZKwgv2rAd6nTVbAm9wmNlf2hWl6CqkwCH4al/nwTGJmmoWVviES+nPsp0UX0H7QEeWkhxMwmdVQNoiMbK44Y5VJ9nVI5fWHudJ9SJ81c2EGVCq3SHLRcMnkckBoMzYsgpEGhRuttILr7ne/Pb10QwpJHEX8CZJX414ddKAh3WJkoVPKefF63AlInKIlWymY/cgLN6w5JvTuMzWA22wiSe19UO78GsamEbdgL3ntQiyHAbVPjNhyv3rbjk8+6hYbe3tZm10uNyXlRwIpAsdOCQWVSMSrDfk0cG/FD643sMzBrm+divCPtz8SVUhfm0zOO8TcE2ug2M+Mt/KSQ9xnE4bUdIARps7qe8FtfKTTU68sxg3QjQ2qtIrorE4GYRyUupCXeRz3Bnk=
        on:
          tags: true
    - stage: github pages publish
      script: "npm run docs:build"
      before_deploy: # allow dist an docs in git
        - sed -i '/dist/d' .gitignore
        - sed -i '/docs/d' .gitignore
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        on:
          branch: master
